development:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: u200682234_bin1
  password: Pleiku@2025
  host: srv612.hstgr.io
  variables:
    time_zone: '+07:00'  
  database: u200682234_bin1
  port: 3306

production:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: u200682234_bin1
  password: Pleiku@2025
  host: srv612.hstgr.io
  variables:
    time_zone: '+07:00'  # Hoặc 'Asia/Ho_Chi_Minh' nếu MySQL hỗ trợ
  database: u200682234_bin1
  port: 3306


test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000